version: "3.3"
services:
  postgres:
    image: kartoza/postgis
    container_name: postgres
    environment:
      - POSTGRES_USER=pgadmin4
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=urbinlab
    volumes: 
      - database-data:/var/lib/postgresql/data/

  main-backend: 
    build: ../../backend/URBinLAB-backend/backend
    container_name: main-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/urbinlab
      - SPRING_DATASOURCE_USERNAME=pgadmin4
      - SPRING_DATASOURCE_PASSWORD=password
    volumes: 
        - ../../data/filesystem:/data/filesystem

  frontend:
    build: ../../frontend/URBinLAB-frontend/frontend
    container_name: frontend
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment: 
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
        - '1000:80'
    volumes: 
        - pgadmin:/root/.pgadmin

  aux-backend:
    build: ../../backend/URBinLAB-backend/auxiliary
    container_name: aux-backend
    depends_on:
      - elastic-search
    ports:
      - "5050:5050"
    volumes:
      - ../../data/dictionary.txt:/data/dictionary.txt

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elastic-search
    environment:
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
      - "ingest.geoip.downloader.enabled=false"
      - "discovery.type=single-node"
    #sysctls:
      #- vm.max_map_count=2097152
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../frontend/URBinLAB-frontend/frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend

volumes:
    database-data:
    pgadmin:
    elasticsearch_data: